package insights

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

        // ReceiverStatus enumerates the values for receiver status.
    type ReceiverStatus string

    const (
                // ReceiverStatusDisabled ...
        ReceiverStatusDisabled ReceiverStatus = "Disabled"
                // ReceiverStatusEnabled ...
        ReceiverStatusEnabled ReceiverStatus = "Enabled"
                // ReceiverStatusNotSpecified ...
        ReceiverStatusNotSpecified ReceiverStatus = "NotSpecified"
            )
    // PossibleReceiverStatusValues returns an array of possible values for the ReceiverStatus const type.
    func PossibleReceiverStatusValues() []ReceiverStatus {
        return []ReceiverStatus{ReceiverStatusDisabled,ReceiverStatusEnabled,ReceiverStatusNotSpecified}
    }

