package insightsapi

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
    "context"
    "github.com/Azure/azure-sdk-for-go/services/monitor/mgmt/2021-09-01/insights"
    "github.com/Azure/go-autorest/autorest"
)

        // ActionGroupsClientAPI contains the set of methods on the ActionGroupsClient type.
        type ActionGroupsClientAPI interface {
            CreateOrUpdate(ctx context.Context, resourceGroupName string, actionGroupName string, actionGroup insights.ActionGroupResource) (result insights.ActionGroupResource, err error)
            Delete(ctx context.Context, resourceGroupName string, actionGroupName string) (result autorest.Response, err error)
            EnableReceiver(ctx context.Context, resourceGroupName string, actionGroupName string, enableRequest insights.EnableRequest) (result autorest.Response, err error)
            Get(ctx context.Context, resourceGroupName string, actionGroupName string) (result insights.ActionGroupResource, err error)
            GetTestNotifications(ctx context.Context, notificationID string) (result insights.TestNotificationDetailsResponse, err error)
            ListByResourceGroup(ctx context.Context, resourceGroupName string) (result insights.ActionGroupList, err error)
            ListBySubscriptionID(ctx context.Context) (result insights.ActionGroupList, err error)
            PostTestNotifications(ctx context.Context, notificationRequest insights.NotificationRequestBody) (result insights.ActionGroupsPostTestNotificationsFuture, err error)
            Update(ctx context.Context, resourceGroupName string, actionGroupName string, actionGroupPatch insights.ActionGroupPatchBody) (result insights.ActionGroupResource, err error)
        }

        var _ ActionGroupsClientAPI = (*insights.ActionGroupsClient)(nil)
